name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # Solo se ejecuta si CI y performance tests pasaron
    needs: [build-and-test, performance-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # ----------- Ejemplo: Deploy a Firebase Hosting -----------
      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          echo "Desplegando a Firebase Hosting..."
          firebase deploy --only hosting --project your-firebase-project-id

      # ----------- Ejemplo: Deploy a Vercel -----------
      # - name: Deploy to Vercel
      #   env:
      #     VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      #   run: |
      #     npx vercel --prod --token $VERCEL_TOKEN

      # ----------- Ejemplo: Deploy a Netlify -----------
      # - name: Deploy to Netlify
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   run: |
      #     npx netlify deploy --prod --dir=dist --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN

      - name: Show deployed URL
        run: |
          echo "✅ Deploy completado. URL disponible en Firebase/Vercel/Netlify."
